# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = fmt, lint
min_version = 4.0.0

[vars]
tests_path = {tox_root}/tests

[testenv]
set_env =
    PY_COLORS=1

[testenv:fmt]
description = Apply coding style standards to code
runner = uv-venv-lock-runner
dependency_groups =
    fmt
commands =
    ruff format {[vars]tests_path}
    ruff check --fix {[vars]tests_path}

[testenv:lint]
description = Check code against coding style standards, and static checks
runner = uv-venv-lock-runner
dependency_groups =
    lint
    integration
commands =
    codespell {tox_root}
    ruff check {[vars]tests_path}
    ruff format --check --diff {[vars]tests_path}
    pyright {posargs}

[testenv:integration]
description = Run the rock integration tests
runner = uv-venv-lock-runner
dependency_groups =
    integration
pass_env =
    HOME
    JUJU_*
    KUBECONFIG
    OPCLI_ARTIFACTS_BUILD_YAML
    SPREAD_JOB
commands =
    pytest \
        -v \
        -s \
        --tb native \
        --log-cli-level=INFO \
        {[vars]tests_path}/integration \
        {posargs}
